import { defineConfig } from 'tsdown';

// Each workspace package invokes this configuration from its own directory.
export default defineConfig({
    cwd: process.cwd(),
    entry: ['source/index.ts'],
    outDir: 'distribution',
    format: {
        esm: { dts: {} },
        cjs: { dts: false },
    },
    platform: 'node',
    target: 'node22',
    sourcemap: true,
    clean: true,
    cjsDefault: true,
    exports: false,
    // A type facade preserves `import Client = require(...)` alongside named
    // public types. The declarations themselves are generated by the ESM build.
    copy: [{ from: 'source/commonjs.d.cts', rename: 'index.d.cts' }],
});
